version: 2.1

anchors-definitions:
  - always: &always
      only: /.*/
  - never: &never
      ignore: /.*/
  - pre-release-tag: &pre-release-tag
      only: /^v\d+\.\d+\.\d+\-pre$/
  - release-tag: &release-tag
      only: /^v\d+\.\d+\.\d+$/
  - filter-just-on-pre-release: &filter-just-on-pre-release
      filters:
        tags: *pre-release-tag
        branches: *never
  - filter-also-on-pre-release: &filter-also-on-pre-release
      filters:
        tags: *pre-release-tag
  - filter-just-on-release: &filter-just-on-release
      filters:
        tags: *release-tag
        branches: *never

jobs:
  prepare:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Npm install - root
          command: npm ci
      - run:
          name: Npm install - generate_results
          command: |
            cd generate_results
            npm ci
      - run:
          name: Npm install - frontend
          command: |
            cd frontend
            npm ci
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  
  unit-tests:
    docker:
      - image: cimg/node:lts
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Unit tests - generate_results
          command: |
            cd generate_results
            npm run test-ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ../reports/
            JEST_JUNIT_OUTPUT_NAME: generate-results-unit.xml
            JEST_JUNIT_ADD_FILE_ATTRIBUTE: "true"
      - run:
          name: Integration tests - generate_results
          command: |
            cd generate_results
            npm run functional-test-ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ../reports/
            JEST_JUNIT_OUTPUT_NAME: generate-results-integration.xml
            JEST_JUNIT_ADD_FILE_ATTRIBUTE: "true"
      - run:
          name: Unit tests - frontend
          command: |
            cd frontend
            npm run test-ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ../reports/
            JEST_JUNIT_OUTPUT_NAME: frontend-unit.xml
            JEST_JUNIT_ADD_FILE_ATTRIBUTE: "true"
      - store_test_results:
          path: ./reports/
  deploy-preparation:
    docker:
      - image: cimg/node:lts # Maybe try lighter image
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Extract new release tag and version
          command: |
            RELEASE_TAG=$(echo "$CIRCLE_TAG" | perl -wne '/^(.*)\-pre$/i and print $1')
            echo $RELEASE_TAG > RELEASE_TAG.txt
            echo "RELEASE_TAG: $RELEASE_TAG"
            RELEASE_VERSION=$(echo "$RELEASE_TAG" | perl -wne '/^v(\d+\.\d+\.\d+)$/i and print $1')
            echo $RELEASE_VERSION > RELEASE_VERSION.txt
            echo "RELEASE_VERSION: $RELEASE_VERSION"
      - run:
          name: Point to main branch
          command: git checkout configure-automatic-deployment # TODO Should be "main"
      - run:
          name: Npm audit - generate_results
          command: cd generate_results && npm audit
      - run:
          name: Npm audit - frontend
          command: cd frontend && npm audit
      - run:
          name: Update version in package files
          command: |
            RELEASE_TAG=$(<RELEASE_TAG.txt)
            RELEASE_VERSION=$(<RELEASE_VERSION.txt)
            chmod a+x ./update_package_json_version.sh
            ./update_package_json_version.sh ./package.json $RELEASE_VERSION
            ./update_package_json_version.sh ./generate_results/package.json $RELEASE_VERSION
            ./update_package_json_version.sh ./frontend/package.json $RELEASE_VERSION
      - run:
          name: Commit new version
          command: |
            git config user.email "sambuccid@gmail.com"
            git config user.name "CircleCI Deploy"
            git add package.json
            git add generate_results/package.json
            git add frontend/package.json
            git commit -m "Automatic update of package versions from CircleCI [skip ci]"
            git push
      # TODO re-introduce the step, maybe circleci issue with "config file could not be located" has been resolved
      #- run:
      #    name: Git Tag Release
      #    command: |
      #      RELEASE_TAG=$(<RELEASE_TAG.txt)
      #      RELEASE_VERSION=$(<RELEASE_VERSION.txt)
      #      git tag -a $RELEASE_TAG -m "Release version $RELEASE_VERSION"
      #      git push --tags
      
      # TODO add rule for github for add tags just on main
  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Copy readmes to npm packages
          command: |
            cp README.md generate_results/README.md
            cp README.md frontend/README.md
      - run:
          name: Placeholder
          command: |
            echo "Placeholder"
            echo $NPM_TOKEN | cut -c1-6
      # TODO npm publish

workflows:
  workflow:
    jobs:
      - prepare:
          <<: *filter-also-on-pre-release
      - unit-tests:
          requires:
            - prepare
          <<: *filter-also-on-pre-release
      - deploy-preparation:
          requires:
            - unit-tests
          <<: *filter-just-on-pre-release
      - deploy:
          <<: *filter-just-on-release
