version: 2.1

jobs:
  prepare:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Npm install - root
          command: npm ci
      - run:
          name: Npm install - generate_results
          command: |
            cd generate_results
            npm ci
      - run:
          name: Npm install - frontend
          command: |
            cd frontend
            npm ci
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  
  unit-tests:
    docker:
      - image: cimg/node:lts
    steps:
      - attach_workspace:
          at: ~/project
      # TODO maybe add npm audit?
      - run:
          name: Unit tests - generate_results
          command: |
            cd generate_results
            npm test
      - run:
          name: Unit tests - frontend
          command: |
            cd frontend
            npm test
  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - attach_workspace:
          at: ~/project

workflows:
  workflow:
    jobs:
      - prepare
      - unit-tests:
          requires:
            - prepare
      - deploy:
          requires:
            - unit-tests
          filters: &filter-to-deploy
            tags:
              only: /.*/
            branches:
              ignore: /.*/
